---
title: "Lab 03 - Nobel laureates"
author: "Lindsay Stall"
date: "01/20/2023"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1

```{rview}
view(nobel)

```


There are 935 observations, and 26 variables. Each row represents information of a different nobel prize winning scientist.

### Exercise 2

```{r}
nobel_living <- nobel

nobel_living %>% 

  filter(country != "NA") %>%

  filter(gender != "org") %>%

  filter(is.na(died_date))
```


### Exercise 3

```{r}
nobel_living <- nobel_living %>%
  mutate(
    country_us = if_else(country == "USA", "USA", "Other")
  )
```

```{r}
nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))
```

```{r}
ggplot(nobel_living_science, aes(y = country_us))+
geom_bar()+
facet_wrap(~category, ncol = 1)
```



### Exercise 4

...

### Exercise 5

...

### Exercise 6

...
